apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-auth
rules:

# Pod
- apiGroups:
  - ""
  resources:
  - pods/attach
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - pods/attach
  - pods/exec
  - pods/proxy
  - pods/portforward
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch


- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch


- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - watch

#Deployment
- apiGroups:
  - apps
  resources:
  - deployments/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - apps
  resources:
  - deployments/rollback
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update

- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - watch  
  
- apiGroups:
  - extensions
  resources:
  - deployments/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - extensions
  resources:
  - deployments/rollback
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update

- apiGroups:
  - extensions
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - watch  


# endpoint

- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

# Configmap
- apiGroups:
  - ""
  resources:
  - confimaps
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch


# hpa
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers/status
  verbs:
  - get
  - list
  - watch


# services

- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch


- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - list
  - watch

 # service account 

- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch


# roles
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch


# role binding

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

# events

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch

# secrets

- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch


# namespaces

- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - list
  - watch

# node

- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch

# pvc   

- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch


# replicacion controller

- apiGroups:
  - ""
  - extensions
  resources:
  - replicationcontrollers/scale
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - replicationcontrollers/status
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch


 # Daemon Sets 

- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - extensions
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - extensions
  resources:
  - daemonsets/status
  verbs:
  - get
  - list
  - watch

# replica set


- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets/status
  verbs:
  - get
  - list
  - watch


- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# stateful sets

- apiGroups:
  - apps
  resources:
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch


# cronjobs

- apiGroups:
  - batch
  resources:
  - cronjobs/status
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch



# jobs

- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch



# ingress

- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - list
  - watch


# network policies

- apiGroups:
  - networking.k8s.io
  - extensions

  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch


# pod disruption budget

- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/status
  verbs:
  - get
  - list
  - watch


# limit ranges
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - watch



# bindings

- apiGroups:
  - ""
  resources:
  - bindings
  verbs:
  - get
  - list
  - watch



# resource quotas

- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - ""
  resources:
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch  

 # controller revisions 

- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - watch  

 # service account 

- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate

# roles
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# role binding

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# clusterRoleBinding

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# clusterRole

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

# localsubjectaccessreviews

- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
