apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-auth-role
rules:

  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-auth
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: kube-auth-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: kube-auth
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-auth-rolebinding
subjects:
- kind: ServiceAccount
  name: kube-auth
  namespace: default
  apiGroup: ''
roleRef:
  kind: ClusterRole
  name: kube-auth-role
  apiGroup: rbac.authorization.k8s.io